### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [larsdroid/Player#1]
Hello, I would like to design a logo for your project. Do you have a logo? I can give some ideas if you are interested?
Greetings
Nuno

**Comment by larsdroid** [comment]
Hi Nuno,
Yes, sounds good!
I have a simple app icon I made myself, but it's not that good: [https://github.com/larsdroid/Player/tree/master/icon](https://github.com/larsdroid/Player/tree/master/icon)

The app has a focus on *whole albums* instead of individual songs. So some concept of an album (disc/vinyl/...) would be nice.

Greetings,
Lars

**Comment by nunojesus** [comment]
Hello, I design this logos, they almost the same, but the 1st one is more rounded.
I mix a vinyl with a play button.
Say if your lijke it or not, and if you want to change something, like the colors for example.

![1](https://user-images.githubusercontent.com/34600369/39400292-ddd40908-4b25-11e8-98f5-e7bfc28504eb.png)

**Comment by larsdroid** [comment]
Thanks! An original concept!
I like it, but didn't realize that the design represented a play button on the right side. Can you perhaps give play button a different background color? I (currently) have two primary colors: the yellow and purple colors that can be seen in my original app icons. I'm thinking the play button in purple and the center of the vinyl in yellow.

I would opt for the second version since it's a true play button.

Also, can you set the same distance between the white reflection lines on the left?

**Comment by larsdroid** [comment]
I'm using these colors:
```
#aa00ff
#7b1fa2
#ffa726
```

**Comment by nunojesus** [comment]
Hi, I will do the changes tonight, and I will put it here, can you send me a image of your app icon and some screenshots from the app? This app it will be on the google play and apple stote? Thanks

**Comment by nunojesus** [comment]
I saw the icon app in the link that you send me, do you have a name  (brand name) for the app already ?

**Comment by larsdroid** [comment]
Yes, the plan is to put the app on the Play store. (not the Apple store since it's an Android native app).
The brand name I have in mind is "Album Player". However, it turns out that there is already an app with this exact name, so I'm not sure if this name is going to accepted.

I'll put up some screenshots and reference them in the README.

**Comment by nunojesus** [comment]
See if you like the changes.
![playerpurple1](https://user-images.githubusercontent.com/34600369/39447900-225217d2-4cbb-11e8-8283-f456bc38e866.png)

**Comment by larsdroid** [comment]
Looking good! I like the middle one best (with the blue background).

I'm thinking that having the play button stick out would make it more obvious that it is a play button.
What do you think of having the vinyl (circle) in the original grey color and having the actual play button (just the large triangle) in purple? ... with the play button on top.
Perhaps the pickup needle would have to be moved slightly so that it doesn't get covered by the play button.

Can you do a drop shadow to the bottom right corner such as [in these examples](https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto/gigs/54798074/original/98387688a4e44e44dfa8064ae9cd61df6cfb5488/do-modern-app-icon.jpg)? :)

**Comment by nunojesus** [comment]
I start working in the changes but Im busy with work this last days, but I will try to send you the changes tonight or tomorrow.

**Comment by nunojesus** [comment]
Hi, here are the changes that you want, see if it´s that what you want, the name of your project is just player?
![logo final](https://user-images.githubusercontent.com/34600369/39667837-b156620e-50b6-11e8-9b1f-82a6f3e914a6.png)

**Comment by larsdroid** [comment]
Thanks, looking good! :)
I'm thinking of using the name "Album Player". I hope such a name gets accepted.

**Comment by nunojesus** [comment]
Do you want to put that name in the logo?

**Comment by larsdroid** [comment]
Hmm, probably better not. Without the name in there I can always change it later.
I'm thinking of using the bottom left one (with the blue background) as app Icon. I'll use the first logo in the about screen or splash screen. Do you have [different sizes](http://iconhandbook.co.uk/reference/chart/android/)?

**Comment by nunojesus** [comment]
What sizes do you want?
Is this what you want?
48 × 48 (mdpi)
72 × 72 (hdpi)
96 × 96 (xhdpi)
144 × 144 (xxhdpi)
192 × 192 (xxxhdpi)
512 × 512 (Google Play store)

**Comment by larsdroid** [comment]
That would be awesome :)

**Comment by nunojesus** [comment]
Is this what you want,?

![icon](https://user-images.githubusercontent.com/34600369/39715011-b7b1fc76-5223-11e8-98e3-42fc0f917130.png)
![logo](https://user-images.githubusercontent.com/34600369/39715012-b7ed23c8-5223-11e8-8eb9-4f3434aebee8.png)
![logotype_horizontal](https://user-images.githubusercontent.com/34600369/39715013-b80fe4a8-5223-11e8-9175-e5c6fc51852f.png)
![logotype_vertical](https://user-images.githubusercontent.com/34600369/39715014-b83911de-5223-11e8-99f5-acb118f65331.png)
![48px](https://user-images.githubusercontent.com/34600369/39715020-bdcfd696-5223-11e8-88df-14309bdd7a1e.png)
![72px](https://user-images.githubusercontent.com/34600369/39715021-bdeffde0-5223-11e8-8a27-d87fd3a5d3aa.png)
![96px](https://user-images.githubusercontent.com/34600369/39715022-be16972a-5223-11e8-9b49-a98607c64383.png)
![144px](https://user-images.githubusercontent.com/34600369/39715023-be3aa6c4-5223-11e8-883c-7b0817326a1c.png)
![192px](https://user-images.githubusercontent.com/34600369/39715024-be58fc64-5223-11e8-9c0d-40626d434cf5.png)
![512px](https://user-images.githubusercontent.com/34600369/39715025-be7831b0-5223-11e8-86b2-4b6f91211a7b.png)

**Comment by larsdroid** [comment]
Yep, great, moving them into the source tree now.

**Comment by larsdroid** [comment]
Ok, I've added them.
On newer versions of Android, round icons are being used instead of square icons. Would you like to create a round set of icons as well? ([See google link](https://developer.android.com/about/versions/nougat/android-7.1#circular-icons))

**Comment by nunojesus** [comment]
Hello I create a pull request with all the files even with the new icon with different sizes.
If you need more just say it, I saw in your profile that you have others projects, if you want I can also contribute.

greetings

**Comment by nunojesus** [comment]
Hi I saw your profile and you have other great projects related to music, I would like to create logo design for them if you want.

This are the repositories of the projects

- https://github.com/larsdroid/albums
- https://github.com/larsdroid/mp3-vbr-length

**Comment by larsdroid** [comment]
Thanks for the offer. Unfortunately these projects are either too small to warrant a logo or not yet fit for release. There's still a lot to be done for the other albums project.

**Comment by nunojesus** [comment]
Ok, if you need something just say it, my email is jesus.nunojose@gmail.com. cheers!

**Comment by larsdroid** [comment]
Thank you very much for your contribution!
